# Generated by Django 4.1.7 on 2024-02-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='product_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
