# Generated by Django 4.1.7 on 2024-02-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cartitems_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='product_slug',
        ),
    ]
