# Generated by Django 4.1.7 on 2024-05-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_cart_razorpay_order_id_cart_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart',
            new_name='carts',
        ),
    ]
