# Generated by Django 4.1.7 on 2024-05-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_cart_cartitems_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='carts',
            new_name='cart',
        ),
    ]
