# Generated by Django 4.1.7 on 2024-05-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_carts_cartitems_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField(max_length=20)),
                ('emp_name', models.CharField(max_length=50)),
            ],
        ),
    ]
