# Generated by Django 4.1.7 on 2024-05-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
