# Generated by Django 4.1.7 on 2024-03-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='min_amt',
            new_name='minimum_amount',
        ),
    ]
